version: 2
jobs:
  build:
    
    working_directory: ~/circleci-demo-java-spring

    docker:
      - image: circleci/openjdk:latest
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: studhub_app
          POSTGRES_DB: studhub
          POSTGRES_PASSWORD: 1234

    steps:
      - run:
          name: Setup PSQL Databases
          command: |
            sudo rm -rf /var/lib/apt/lists/* && sudo apt update
            sudo apt-get update
            sudo apt install -y postgresql-client
            createdb -h localhost studhub_test -O studhub_app

      - checkout
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/studhub-0.0.1-SNAPSHOT.jar
